require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'


Layout/EndOfLine:
  EnforcedStyle: lf

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/ClassStructure:
  Enabled: true


Lint/EmptyClass:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false


Metrics:
  Enabled: false


Naming/VariableNumber:
  Enabled: false


Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
